### ISSUE TITLE
https://electrum-dash.org/ appears to have invalid certificate

### ISSUE THREAD

**Issue by wmerfalen** [Bertrand256/electrum-dash#5]
Hello,

It appears the electrum-dash.org URL seems to have an invalid ssl cert. 

https://electrum-dash.org/

**Comment by Bertrand256** [comment]
> It appears the electrum-dash.org URL seems to have an invalid ssl cert.

I'm not in control of that domain and cannot really do anything about it.

**Comment by Bertrand256** [comment]
I'm closing the issue as unrelated to the Electrum Dash application.
